name: Add Repository to App

on:
  workflow_dispatch:

jobs:
  add-to-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add repository to app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        APP_ID=853518
        INSTALLATION_ID=48299343
        REPOS=api # List of repositories to add

        # Function to get a JWT token for GitHub App authentication
        get_jwt() {
          jwt=$(curl -s --request POST \
            --url "https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens" \
            --header "Authorization: Bearer $GH_TOKEN" \
            --header "Accept: application/vnd.github.v3+json" \
            --data "{}" | jq -r '.token')
          echo $jwt
        }

        JWT_TOKEN=$(get_jwt)

        for REPO in "${REPOS[@]}"; do
          curl -X PATCH \
            -H "Authorization: Bearer $JWT_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            --url "https://api.github.com/app/installations/$INSTALLATION_ID/repositories/$REPO" \
            --data '{"permissions": {"contents": "read"}}'
          echo "Added $REPO to GitHub App."
        done
