name: Add Repository to App

on:
  workflow_dispatch:

jobs:
  add-to-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add repository to app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Set variables
        INSTALLATION_ID="48299343"
        REPO_NAME="api"
        API_URL="https://api.github.com"

        # Add repository to app installation
        curl -X PUT \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.machine-man-preview+json" \
          "$API_URL/app/installations/$INSTALLATION_ID/repositories/$REPO_NAME"
