name: Add Repository to GitHub App

#on:
#  push:
#    branches:
#      - main

jobs:
  add-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: add repo to app
      run: |
           curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/user/installations/48299343/repositories/api

