name: Add Repository to App

on:
  workflow_dispatch:

jobs:
  add-to-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add repository to app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Set variables
        APP_ID="48299343"
        REPO_NAME="api"
        API_URL="https://api.github.com"

        # Add repository to app (replace this with the actual API request or script you need)
        curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "$API_URL/apps/$APP_ID/add_repositories" \
          -d "{\"repository_ids\": [\"$REPO_NAME\"]}"
