name: Add Repository to GitHub App

on:
  push:
    branches:
      - main

jobs:
  add-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: add repo to app
      run: |
           curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/user/installations/48299343/repositories/767945234
