name: Add Repository to GitHub App

on:
  push:
    branches:
      - main

jobs:
  add-repo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Repository to GitHub App
        env:
          APP_ID: 853518
          INSTALLATION_ID: 48299343
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REPOSITORY_NAME: 'api'
        run: |
          ACCESS_TOKEN=$(curl -X POST -H "Authorization: Bearer $(jwt)" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/app/installations/${INSTALLATION_ID}/access_tokens" | jq -r '.token')
          curl -X PUT -H "Authorization: token $ACCESS_TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/installation/repositories/${REPOSITORY_NAME}"
