name: Auto-comment

on:
  issues:
    types:
      - opened

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Auto-comment on issue
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueNumber = context.payload.issue.number;
          const repoOwner = context.repo.owner;
          const repoName = context.repo.repo;
          const commentBody = 'Thank you for opening this issue!';

          github.issues.createComment({
            issue_number: issueNumber,
            owner: repoOwner,
            repo: repoName,
            body: commentBody
          });
