name: Auto Comment on Issue

on:
  issues:
    types:
      - opened

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Comment on issue
        run: |
          echo "Thank you for opening this issue!" > comment.md
          gh issue comment ${{ github.event.issue.number }} --body-file=comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
