name: autocomment

on:
  issues:
    types:
      - opened

jobs:
  auto-close:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Close issue with comment
        run: |
          if [[ ${{ github.event.comment.body }} == "close" ]]; then
            echo "This issue is being closed." > comment.md
            gh issue comment ${{ github.event.issue.number }} --body-file=comment.md
            gh issue close ${{ github.event.issue.number }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
