name: Auto Comment on Issue

on:
  issues:
    types:
      - opened

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Comment on issue
        run: node comment.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
