name: Auto-comment

on:
  issues:
    types:
      - opened

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Auto-comment on new issue
      uses: peter-evans/create-issue-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Thank you for opening this issue! We'll look into it.
