name: Add Member to org-members

on:
  issue_comment:
    types: [created]

jobs:
  process-comment:
    runs-on: ubuntu-latest
    if: github.event.issue.number == 157  # Replace 157 with the issue number
    steps:
      - uses: actions/checkout@v2

      - name: GitHub_ID provided in comment 
        run: |
          echo "Provided GitHub_ID is: ${{ github.event.comment.body }}"

      - name: Extract GITHUB_ID
        id: extract
        run: |
          echo "${{ github.event.comment.body }}" > comment.txt
          cat comment.txt  # Check the content of comment.txt
          GITHUB_ID=$(cat comment.txt | cut -d' ' -f2)  # Extract the variable using cut
          echo "Extracted GITHUB_ID: $GITHUB_ID"
          echo "GITHUB_ID=$GITHUB_ID" >> $GITHUB_ENV  # Set the environment variable using Environment Files

      - name: Add Member to org-members team.
        run: |
          # Set organization name, username, and token
          ORG_NAME="myorgpradeem"
          MY_TEAM="myteam"
          USERNAME="$GITHUB_ID"
          TOKEN="${{ secrets.API_TOKEN }}"
          
          # Make request to GitHub API
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/$ORG_NAME/members/$USERNAME")

          # Check Response Status
          if [ $response -eq 204 ]; then
            echo "$USERNAME is already a member of $ORG_NAME." > comment.md
            gh issue comment ${{ github.event.issue.number }} --body-file=comment.md
          elif [ $response -eq 404 ]; then
            echo "$USERNAME is not found in $ORG_NAME. Adding $USERNAME to $MY_TEAM." > comment.md
            gh team add --team $MY_TEAM --member $USERNAME
            gh issue comment ${{ github.event.issue.number }} --body-file=comment.md
          else
            echo "Error: HTTP status code $response"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
