name: Check Org Private Members

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to check membership for'
        required: true

jobs:
  check_membership:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: echo "machine github.com login ${{ secrets.API_TOKEN }}" > ~/.netrc

    - name: Check Membership
      run: |
        ORG_NAME="myorgpradeem"
        USERNAME="${{ github.event.inputs.username }}"
        membership=$(curl -s -H "Authorization: token ${{ secrets.API_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/orgs/$ORG_NAME/members/$USERNAME")
        is_private=$(echo "$membership" | grep -o '"type": *"[^"]*"' | grep -o '"[^"]*"$')
        if [ "$is_private" == "\"User\"" ]; then
          echo "$USERNAME is a private member of $ORG_NAME."
        else
          echo "$USERNAME is not a private member of $ORG_NAME."
        fi
      env:
        ORG_NAME: myorgpradeem
