name: Check Org Private Members

on:
  workflow_dispatch:

jobs:
  check_membership:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: echo "machine github.com login ${{ secrets.API_TOKEN }}" > ~/.netrc

    - name: Get Org Members
      id: get_members
      run: |
        ORG_NAME="myorgpradeem"
        members=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Accept: application/vnd.github.v3+json" \
                   "https://api.github.com/orgs/$ORG_NAME/members")
        is_private=$(echo "$members" | grep -c '"type": *"User"')
        if [ "$is_private" -eq 0 ]; then
          echo "The organization $ORG_NAME does not have private members."
        else
          echo "The organization $ORG_NAME has private members."
        fi
        
