name: Issue Data Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  process-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Variables
        id: extract
        run: |
          echo "${{ github.event.comment.body }}" > comment.txt
          # Parse comment.txt to extract variables and set them as environment variables
          # Example:
          export VAR_NAME=$(grep -oP 'VAR_NAME=\K[^ ]+' comment.txt)

      - name: Use Variables
        run: |
          echo "Extracted Variable: $VAR_NAME"
