name: Issue Data Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Extract Variables
      id: extract
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.API_TOKEN }}
        script: |
          const issueBody = context.payload.issue.body;
          if (issueBody) {
            const match = issueBody.match(/Variable: (.*)/);
            const extractedVariable = match ? match[1].trim() : null;
            console.log('Extracted Variable:', extractedVariable);
            return { variable: extractedVariable };
          } else {
            console.log('Issue body is null.');
            return { variable: null };
          }
          

    - name: Use Extracted Variable
      run |
        echo "Variable from Issue: ${{ steps.extract.outputs.variable }}"
