name: Issue Comment Variables

on:
  issue_comment:
    types: [created]

jobs:
  process-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Comment Content
        run: |
          echo "Comment Content: ${{ github.event.comment.body }}"

      - name: Extract Variables
        id: extract
        run: |
          echo "${{ github.event.comment.body }}" > comment.txt
          cat comment.txt  # Check the content of comment.txt
          export VAR_NAME=$(cat comment.txt | cut -d' ' -f2)  # Export the variable using cut
          echo "Extracted Variable: $VAR_NAME"
          echo "::set-env name=VAR_NAME::$VAR_NAME"  # Set the environment variable for subsequent steps

      - name: Use Variables
        run: |
          echo "Extracted Variable: $VAR_NAME"
