name: Issue Comment Variables

on:
  issue_comment:
    types: [created]

jobs:
  process-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Variables
        id: extract
        run: |
          echo "${{ github.event.comment.body }}" > comment.txt
          export VAR_NAME=$(grep -oP 'VAR_NAME=\K[^ ]+' comment.txt)

      - name: Use Variables
        run: |
          echo "Extracted Variable: $VAR_NAME"
